using DataLayer.Tables;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DataLayer.MapTables
{
    public class FormatMap
    {
        public FormatMap()
        {

        }
        public void SeedData(EntityTypeBuilder<Format> entity)
        {
            entity.HasData(new Format() { Id = 1, Name = "cap" });
            entity.HasData(new Format() { Id = 2, Name = "coated-tab" });
            entity.HasData(new Format() { Id = 3, Name = "supp" });
            entity.HasData(new Format() { Id = 4, Name = "syrup" });
            entity.HasData(new Format() { Id = 5, Name = "cream" });
            entity.HasData(new Format() { Id = 6, Name = "tab" });
            entity.HasData(new Format() { Id = 7, Name = "susp" });
            entity.HasData(new Format() { Id = 10, Name = "effervi-tab" });
            entity.HasData(new Format() { Id = 11, Name = "oint" });
            entity.HasData(new Format() { Id = 12, Name = "gel" });
            entity.HasData(new Format() { Id = 13, Name = "solu" });
            entity.HasData(new Format() { Id = 14, Name = "oral-vial" });
            entity.HasData(new Format() { Id = 15, Name = "SR-tab" });
            entity.HasData(new Format() { Id = 16, Name = "gargle" });
            entity.HasData(new Format() { Id = 17, Name = "nasal-spray" });
            entity.HasData(new Format() { Id = 18, Name = "coated-tab plastic-bottle" });
            entity.HasData(new Format() { Id = 19, Name = "nasal-gel" });
            entity.HasData(new Format() { Id = 20, Name = "cap for inhal" });
            entity.HasData(new Format() { Id = 21, Name = "oral-drop" });
            entity.HasData(new Format() { Id = 22, Name = "dry-syrup" });
            entity.HasData(new Format() { Id = 23, Name = "MR-tab" });
            entity.HasData(new Format() { Id = 24, Name = "oral-gel" });
            entity.HasData(new Format() { Id = 25, Name = "DR-cap" });
            entity.HasData(new Format() { Id = 26, Name = "sachet" });
            entity.HasData(new Format() { Id = 27, Name = "dose nasal-spray" });
            entity.HasData(new Format() { Id = 28, Name = "inh-cap" });
            entity.HasData(new Format() { Id = 29, Name = "caplet" });
            entity.HasData(new Format() { Id = 30, Name = "caplet in plastic-cont" });
            entity.HasData(new Format() { Id = 31, Name = "gum" });
            entity.HasData(new Format() { Id = 32, Name = "dispersable-tab" });
            entity.HasData(new Format() { Id = 33, Name = "SR-coated-tab" });
            entity.HasData(new Format() { Id = 34, Name = "SR-cap" });
            entity.HasData(new Format() { Id = 35, Name = "vag-solu" });
            entity.HasData(new Format() { Id = 36, Name = "chew-tab" });
            entity.HasData(new Format() { Id = 37, Name = "ovule" });
            entity.HasData(new Format() { Id = 38, Name = "vag-ovule" });
            entity.HasData(new Format() { Id = 39, Name = "vag-cream" });
            entity.HasData(new Format() { Id = 40, Name = "nail-solu" });
            entity.HasData(new Format() { Id = 41, Name = "oral-paste" });
            entity.HasData(new Format() { Id = 42, Name = "ear-drop" });
            entity.HasData(new Format() { Id = 43, Name = "amp" });
            entity.HasData(new Format() { Id = 44, Name = "vial" });
            entity.HasData(new Format() { Id = 45, Name = "eye-oint" });
            entity.HasData(new Format() { Id = 46, Name = "rectal-cream" });
            entity.HasData(new Format() { Id = 47, Name = "dry-vial" });
            entity.HasData(new Format() { Id = 48, Name = "emultion" });
            entity.HasData(new Format() { Id = 49, Name = "enema" });
            entity.HasData(new Format() { Id = 50, Name = "vag-douch" });
            entity.HasData(new Format() { Id = 51, Name = "XR-tab" });
            entity.HasData(new Format() { Id = 52, Name = "vag-tab" });
            entity.HasData(new Format() { Id = 53, Name = "elexir" });
            entity.HasData(new Format() { Id = 54, Name = "vag-douch + app" });
            entity.HasData(new Format() { Id = 55, Name = "lotion" });
            entity.HasData(new Format() { Id = 56, Name = "mouth-wash" });
            entity.HasData(new Format() { Id = 57, Name = "cartridge" });
            entity.HasData(new Format() { Id = 58, Name = "coated-tab+loz" });
            entity.HasData(new Format() { Id = 59, Name = "loz" });
            entity.HasData(new Format() { Id = 60, Name = "dental-cartridge" });
            entity.HasData(new Format() { Id = 61, Name = "gum-tab" });
            entity.HasData(new Format() { Id = 62, Name = "plast-oral-drop" });
            entity.HasData(new Format() { Id = 63, Name = "chew-gum" });
            entity.HasData(new Format() { Id = 64, Name = "powder" });
            entity.HasData(new Format() { Id = 65, Name = "سوار للمعصم" });
            entity.HasData(new Format() { Id = 66, Name = "salt" });
            entity.HasData(new Format() { Id = 67, Name = "shampoo" });
            entity.HasData(new Format() { Id = 68, Name = "rectal-oint" });
            entity.HasData(new Format() { Id = 69, Name = "nasal-drop" });
            entity.HasData(new Format() { Id = 70, Name = "sublingual-tab" });
            entity.HasData(new Format() { Id = 71, Name = "soap" });
            entity.HasData(new Format() { Id = 72, Name = "balsam" });
            entity.HasData(new Format() { Id = 73, Name = "spray" });
            entity.HasData(new Format() { Id = 74, Name = "aerosol-spray" });
            entity.HasData(new Format() { Id = 75, Name = "DR-tab" });
            entity.HasData(new Format() { Id = 76, Name = "vial+amp+lido" });
            entity.HasData(new Format() { Id = 77, Name = "vial+W.F.I." });
            entity.HasData(new Format() { Id = 78, Name = "vial+water-amp" });
            entity.HasData(new Format() { Id = 79, Name = "vial+amp" });
            entity.HasData(new Format() { Id = 80, Name = "eye-drop" });
            entity.HasData(new Format() { Id = 81, Name = "aplicapeye-oint" });
            entity.HasData(new Format() { Id = 82, Name = "gel-cap" });
            entity.HasData(new Format() { Id = 83, Name = "soft-cap" });
            entity.HasData(new Format() { Id = 84, Name = "vial+lido" });
            entity.HasData(new Format() { Id = 85, Name = "dental-gel" });
            entity.HasData(new Format() { Id = 86, Name = "vag-gel" });
            entity.HasData(new Format() { Id = 87, Name = "XR-coated-tab" });
            entity.HasData(new Format() { Id = 88, Name = "serum+urocap" });
            entity.HasData(new Format() { Id = 89, Name = "serum+urocap+2way" });
            entity.HasData(new Format() { Id = 90, Name = "vag soft-gel-cap" });
            entity.HasData(new Format() { Id = 91, Name = "plastic-amp eye-drop" });
            entity.HasData(new Format() { Id = 92, Name = "dry-susp" });
            entity.HasData(new Format() { Id = 93, Name = "ER-tab" });
            entity.HasData(new Format() { Id = 94, Name = "serum" });
            entity.HasData(new Format() { Id = 95, Name = "bi-tab" });
            entity.HasData(new Format() { Id = 96, Name = "soft-gel-cap" });
            entity.HasData(new Format() { Id = 97, Name = "coated-tab in plastic-bottle" });
            entity.HasData(new Format() { Id = 98, Name = "bottle" });
            entity.HasData(new Format() { Id = 99, Name = "bag" });
            entity.HasData(new Format() { Id = 100, Name = "plastic-amp" });
            entity.HasData(new Format() { Id = 101, Name = "plastic-vial" });
            entity.HasData(new Format() { Id = 102, Name = "syrup in plastic-dose" });
            entity.HasData(new Format() { Id = 103, Name = "tooth-paste" });
            entity.HasData(new Format() { Id = 104, Name = "surup" });
            entity.HasData(new Format() { Id = 105, Name = "syrup single-dose" });
            entity.HasData(new Format() { Id = 106, Name = "plastic single-dose" });
            entity.HasData(new Format() { Id = 107, Name = "foam" });
            entity.HasData(new Format() { Id = 108, Name = "disinteg-tab" });
            entity.HasData(new Format() { Id = 109, Name = "coated-tab alum-strip" });
            entity.HasData(new Format() { Id = 110, Name = "pre-filled syringe" });
            entity.HasData(new Format() { Id = 111, Name = "coated-tab in plstic-bottle" });
            entity.HasData(new Format() { Id = 112, Name = "coated-tab in Alu" });
            entity.HasData(new Format() { Id = 113, Name = "plstic-amp" });
            entity.HasData(new Format() { Id = 114, Name = "powder-sachet" });
            entity.HasData(new Format() { Id = 115, Name = "powder-spray" });
            entity.HasData(new Format() { Id = 116, Name = "vial+2W.F.I." });
            entity.HasData(new Format() { Id = 117, Name = "vial+1W.F.I. 5ml" });
            entity.HasData(new Format() { Id = 118, Name = "vial+2W.F.I. 2ml" });
            entity.HasData(new Format() { Id = 119, Name = "oral-drops" });
            entity.HasData(new Format() { Id = 120, Name = "ear+nasal-drop" });
            entity.HasData(new Format() { Id = 121, Name = "eye+ear-drop" });
            entity.HasData(new Format() { Id = 122, Name = "vial-plastic" });
            entity.HasData(new Format() { Id = 123, Name = "gelatin-cap" });
            entity.HasData(new Format() { Id = 124, Name = "cap in plastic-bottle" });
            entity.HasData(new Format() { Id = 125, Name = "cap in blister" });
            entity.HasData(new Format() { Id = 126, Name = "cap/sachet" });
            entity.HasData(new Format() { Id = 127, Name = "emul-gel" });
            entity.HasData(new Format() { Id = 128, Name = "tab-plister" });
            entity.HasData(new Format() { Id = 129, Name = "rect-oint" });
            entity.HasData(new Format() { Id = 130, Name = "tab in plastic-bottle" });
            entity.HasData(new Format() { Id = 131, Name = "liquied-soap" });
            entity.HasData(new Format() { Id = 132, Name = "mouth-gel" });
            entity.HasData(new Format() { Id = 133, Name = "coated-tab plister" });
            entity.HasData(new Format() { Id = 134, Name = "oint in glass-bottle" });
            entity.HasData(new Format() { Id = 135, Name = "oint in plastic-bottle" });
            entity.HasData(new Format() { Id = 136, Name = "cap in bottle" });
            entity.HasData(new Format() { Id = 137, Name = "coated-tab/sachet" });
            entity.HasData(new Format() { Id = 138, Name = "tab/sachet" });
            entity.HasData(new Format() { Id = 139, Name = "tab in bottle" });
            entity.HasData(new Format() { Id = 140, Name = "coated-tab in bottle" });
            entity.HasData(new Format() { Id = 141, Name = "XR-cap" });
            entity.HasData(new Format() { Id = 142, Name = "PR-tab" });
            entity.HasData(new Format() { Id = 143, Name = "puff" });
            entity.HasData(new Format() { Id = 144, Name = "solu/glass" });
            entity.HasData(new Format() { Id = 145, Name = "solu/plastic" });
            entity.HasData(new Format() { Id = 146, Name = "susp/gls" });
            entity.HasData(new Format() { Id = 147, Name = "ear+eye+nasal-drop" });
            entity.HasData(new Format() { Id = 148, Name = "ear+eye+nasal-oint" });
            entity.HasData(new Format() { Id = 149, Name = "oral-drop glass-bottle" });
            entity.HasData(new Format() { Id = 150, Name = "oral-drop plasrtic-bottle" });
            entity.HasData(new Format() { Id = 151, Name = "eye-wash" });
            entity.HasData(new Format() { Id = 152, Name = "nasal-wash" });
            entity.HasData(new Format() { Id = 153, Name = "eye-gel" });
            entity.HasData(new Format() { Id = 154, Name = "eye+nose-drop" });
            entity.HasData(new Format() { Id = 155, Name = "oral-drop in glass" });
            entity.HasData(new Format() { Id = 156, Name = "oral-drop in plastic" });
            entity.HasData(new Format() { Id = 157, Name = "tab-sachet" });
            entity.HasData(new Format() { Id = 158, Name = "tab in glass-bottle" });
            entity.HasData(new Format() { Id = 159, Name = "dental-paste" });
            entity.HasData(new Format() { Id = 160, Name = "coated-tab in glass-bottle" });
            entity.HasData(new Format() { Id = 161, Name = "solu+spray" });
            entity.HasData(new Format() { Id = 162, Name = "coated-tab glass-bottle" });
            entity.HasData(new Format() { Id = 163, Name = "paste" });
            entity.HasData(new Format() { Id = 164, Name = "eye&ear-drop" });
            entity.HasData(new Format() { Id = 165, Name = "cream-beige" });
            entity.HasData(new Format() { Id = 166, Name = "cream-rose" });
            entity.HasData(new Format() { Id = 167, Name = "eye-solu" });
            entity.HasData(new Format() { Id = 168, Name = "dispers-tab" });
            entity.HasData(new Format() { Id = 169, Name = "oval-tab" });
            entity.HasData(new Format() { Id = 170, Name = "glycerol-gel" });
            entity.HasData(new Format() { Id = 171, Name = "vag-oint" });
            entity.HasData(new Format() { Id = 172, Name = "oral-drop glass-dropper" });
            entity.HasData(new Format() { Id = 173, Name = "oral-drop plastic-dropper" });
            entity.HasData(new Format() { Id = 174, Name = "cartoon" });
            entity.HasData(new Format() { Id = 175, Name = "oral-solu" });
            entity.HasData(new Format() { Id = 176, Name = "cream in plastic-tube" });
            entity.HasData(new Format() { Id = 177, Name = "one-dose-vial" });
            entity.HasData(new Format() { Id = 178, Name = "vag-efferv-tab" });
            entity.HasData(new Format() { Id = 179, Name = "serum in p.v.c. bag+port+butterflycap" });
            entity.HasData(new Format() { Id = 180, Name = "serum in p.v.c. bag+port+vialcap" });
            entity.HasData(new Format() { Id = 181, Name = "serum in p-p-bag+port+vialCap" });
            entity.HasData(new Format() { Id = 182, Name = "serum+port+butterflyCap" });
            entity.HasData(new Format() { Id = 183, Name = "serum+port+butterflyCap+aluBag" });
            entity.HasData(new Format() { Id = 184, Name = "serum+port+vialCap" });
            entity.HasData(new Format() { Id = 185, Name = "plastic-bag" });
            entity.HasData(new Format() { Id = 186, Name = "CR-tab" });
            entity.HasData(new Format() { Id = 187, Name = "MR-cap" });
            entity.HasData(new Format() { Id = 188, Name = "sunLing-tab" });
            entity.HasData(new Format() { Id = 189, Name = "hand-wash" });
            entity.HasData(new Format() { Id = 190, Name = "oil" });
            entity.HasData(new Format() { Id = 191, Name = "cream + applicator" });
            entity.HasData(new Format() { Id = 192, Name = "dose-spray" });
            entity.HasData(new Format() { Id = 193, Name = "hand-gel" });
            entity.HasData(new Format() { Id = 194, Name = "dressing" });
            entity.HasData(new Format() { Id = 195, Name = "milk" });
            entity.HasData(new Format() { Id = 196, Name = "trans-solu" });
            entity.HasData(new Format() { Id = 197, Name = "oral-spray" });
            entity.HasData(new Format() { Id = 198, Name = "lip-stick" });
            entity.HasData(new Format() { Id = 199, Name = "rectal-solu" });
            entity.HasData(new Format() { Id = 200, Name = "derm-solu" });
            entity.HasData(new Format() { Id = 201, Name = "sol + محقن" });
            entity.HasData(new Format() { Id = 202, Name = "gel + applicator" });
            entity.HasData(new Format() { Id = 203, Name = "foam-solu" });
            entity.HasData(new Format() { Id = 204, Name = "nasal spray" });
            entity.HasData(new Format() { Id = 205, Name = "solu+محقن" });
            entity.HasData(new Format() { Id = 206, Name = "ER-cap" });
            entity.HasData(new Format() { Id = 207, Name = "plastic-vial+urocap+2 way" });
            entity.HasData(new Format() { Id = 208, Name = "plastic-vial+urocap" });
            entity.HasData(new Format() { Id = 209, Name = "dry-syrup in-gls" });
            entity.HasData(new Format() { Id = 210, Name = "dry-syrup in-pls" });
            entity.HasData(new Format() { Id = 211, Name = "eye-susp" });
            entity.HasData(new Format() { Id = 212, Name = "alcool-sol" });
            entity.HasData(new Format() { Id = 213, Name = "water-sol" });
            entity.HasData(new Format() { Id = 214, Name = "loz-diet" });
            entity.HasData(new Format() { Id = 215, Name = "puff-nasal-spray" });
            entity.HasData(new Format() { Id = 216, Name = "vag-cream+applic" });
            entity.HasData(new Format() { Id = 217, Name = "oral-granules" });
            entity.HasData(new Format() { Id = 218, Name = "vial-W.F.I." });
            entity.HasData(new Format() { Id = 219, Name = "vial + W.F.I." });
            entity.HasData(new Format() { Id = 220, Name = "rectal-douch" });
            entity.HasData(new Format() { Id = 221, Name = "dental+dermal-spray" });
        }
    }
}
